### ISSUE TITLE
"," vs "." as time separator

### ISSUE THREAD

**Issue by pos42** [krakan/micronomy#31] opened 2020-10-29 13:30 UTC
I see two problems.

# 1
If you by misstake use "," instead of ".", the column summary just skips the ones with "," with silent error. I.e no user notification. 

# 2
If there is hours logged with no minutes, those wont even add to the column total if there is one error in the column.

It would be a good thing to try to help the user...

See attached screenshot
![Screenshot 2020-10-29 at 14 21 07](https://user-images.githubusercontent.com/821362/97580049-1e3d1900-19f3-11eb-8f08-7db65e226888.png)

**Comment by krakan** [comment] 2021-01-07 13:17
Issue number 1 has been fixed for a while now and I just confirmed that the fix is available on https://micronomy.init.se. Please re-open if you can reproduce.
Issue number 2 is basically a duplicate of #3 which is about implementing sane error handling - right now it is (as you noticed) fairly ad hoc.

**Closed by krakan** 2021-01-07 13:17 UTC
